### ISSUE TITLE
Provider Bug in v0.52.2 - GetDeviceKey invoked with null NodeId

### ISSUE THREAD

**Issue by michaelbhughes** [Juniper/terraform-provider-apstra#577]
### Summary
We upgraded to the `v0.52.2` provider (from `v0.50.1`) and encountered a Provider Bug when running our pipelines again for validation. Our codebase had no changes between upgrading the provider.

The complete error message is below. It has to do with the `apstra_datacenter_device_allocation` resource. Something is up with the `device_key` attribute.

In our code line `device_key = each.value.device_key == "" ? null : each.value.device_key # optional`, the `each.value.device_key` attributes have values and are not equal to `""`.

Please take a look in the provider for what might be triggering this error.

#### Error Message
```sh
│ Error: Provider Bug. Please report this issue to the provider maintainers.
│ 
│   with apstra_datacenter_device_allocation.device_allocation["PF-432"],
│   on resource.tf line 83, in resource "apstra_datacenter_device_allocation" "device_allocation":
│   83: resource apstra_datacenter_device_allocation device_allocation {
│ 
│ GetDeviceKey invoked with null NodeId
```

#### Code
```tf
resource apstra_datacenter_device_allocation device_allocation {
    for_each                 = var.device_allocations
    blueprint_id             = data.apstra_datacenter_blueprint.blueprint.id
    node_name                = each.value.name
    device_key               = each.value.device_key == "" ? null : each.value.device_key # optional
    deploy_mode              = each.value.deploy_mode
    initial_interface_map_id = one([for imap in data.terraform_remote_state.common_cluster.outputs.interface_maps: imap.id if (each.value.initial_interface_map_name == imap.name)])
    depends_on   = [
        null_resource.configure_device_properties
    ]
}
```

**Comment by chrismarget-j** [comment]
Thanks, Michael.

We'll look into it.

**Comment by chrismarget-j** [comment]
I think I found the problem here: 0c1fac8fbc33684f7a30cc549f42998df36d6211

I renamed a computed-only attribute from `node_id` to `id` because *I thought* the terraform plugin framework acceptance tests required an `id` field (this resource was developed before we were using the formal acceptance testing system.

Couple of things about that:

- Willy-nilly renaming of attributes (even ones the users don't directly interact with) isn't that great of an idea, especially if you've written the code to error when an expected field is missing.
- The newest release of the testing framework [doesn't require an `id` field anymore](https://github.com/hashicorp/terraform-plugin-framework/blob/bcbb70badb04f3555e70249d63c822a1c786cd56/website/docs/plugin/framework/acctests.mdx#L50C1-L58C1)
