### ISSUE TITLE
apstra_ipv6_pool allocation issue - 0.61.0

### ISSUE THREAD

**Issue by pyspiotr** [Juniper/terraform-provider-apstra#737]
Hello,
   We have tried a new Apstra provider version 0.61.0 as well as 0.60.0 and we got the same error each time. Version 0.59.1 works fine.
 
![IPv6_pool_error_2 (2)](https://github.com/user-attachments/assets/44336d50-dff6-498c-890f-cf967ba0c58b)
![IPv6_pool_error_1](https://github.com/user-attachments/assets/f0001159-4414-49a6-8484-1b8384cb5d63)

resource "apstra_ipv6_pool" "ZAM_DC1_LO0_IPV6" {
  name = "ZAM_DC1_LO0_IPV6"
  subnets = [
    { network = "XXXXXXXXXXXXXX::/56" }
  ]
}
resource "apstra_ipv6_pool" "ZAM_DC1_TRANSFER_EXTERNAL_IPV6" {
  name = "ZAM_DC1_TRANSFER_EXTERNAL_IPV6"
  subnets = [
    { network = "XXXXXXXXXXXXXX::/56" }
  ]
}

Regards,
Piotr

**Comment by chrismarget-j** [comment]
Hi @pyspiotr,

Thank you for opening this issue.

Is the problem consistently reproducible, or is it an intermittent sort of thing?

Thanks!

**Comment by pyspiotr** [comment]
Hi Chris,
    The problem can be reproduce each time.
Regards,
Piotr

W dniu pon., 22.07.2024 o 16:50 chrismarget-j ***@***.***>
napisał(a):

**Comment by chrismarget-j** [comment]
Hi @pyspiotr,

There have been a number of problems with the the various "pool" resources since they were originally conceived. This one seems have cropped up with provider v0.60.0's upgrade of `github.com/hashicorp/terraform-plugin-framework` from v1.5.0 to v1.9.0.

I don't think this problem (or any of the previous ones) are an issue with the plugin framework. Rather, they are fallout from an unfortunate design decision to capture mutable values (percent used, pool state, etc...) as `Computed` (read-only) resource attributes.

There are a handful of reasons that supporting these attributes cause problems. Worse, the *values of these attributes can't really be trusted* because they're only updated when Terraform's plan phase determines a modification to the resource is required. If the resource is never modified after creation, these values are guaranteed to become inaccurate as elements get consumed from the pool.

So, I'm proposing a breaking change to all of the "pool" resources: All *mutable* read-only attributes (`total`, `status`, `used`, etc...) will always be set to `null`.

If values from these attributes are needed in your Terraform project (to select the least-used ASN pool or whatever), you'll need to run the complementary data source for that object. Use of the data source will be an improvement over relying on the resource for these values because data sources are refreshed with each `terraform apply` while resources only get refreshed when the plan phase detects that a modification is required.

Does this work for you, or do you have any concerns about it?

cc: @bwJuniper @rajagopalans @michaelbhughes

**Comment by pyspiotr** [comment]
Hi Chris,
   It will work for me. Thank you.
Regards,
Piotr

**Comment by michaelbhughes** [comment]
Hi Chris,

Thanks for the notice. No concerns from me. 

Regards,
Michael Hughes

**Comment by chrismarget-j** [comment]
v0.62.0 has the changes proposed in this discussion.

Please let me know if it solves the problem?

**Comment by pyspiotr** [comment]
Hi Chris,
   I got the same error as before,
Regards,
Piotr
![IPv6_pool_error_3](https://github.com/user-attachments/assets/ce3c1bbb-fdd1-4fbd-9258-01411220f03a)

**Comment by chrismarget-j** [comment]
Thank you @pyspiotr.

Would you please share the output of `terraform version` run from within the project directory?

**Comment by pyspiotr** [comment]
Hi Chris,
   Here you go: v1.7.5.

![image](https://github.com/user-attachments/assets/80de2def-9dc0-42f6-af5f-47d7f4ccbb77)

Regards,
Piotr

**Comment by chrismarget-j** [comment]
Hey @pyspiotr,

Can you please clarify what's going on with the provider version? You've rolled back to 0.59.1, but got the most recent error with 0.62.0?

Thanks!

**Comment by pyspiotr** [comment]
Hi Chris,
    I rolled back to 0.59.0 after the errror.
Regards,
Piotr

**Comment by chrismarget-j** [comment]
Update: I've reproduced the error:
- terraform 1.7.5
- plugin 0.59.1
- create an IPv6 pool
- upgrade plugin to 0.62.0
- `terraform apply`

Will keep you posted.

**Comment by chrismarget-j** [comment]
Update 2: The same process does not produce an error with terraform 1.9.0 (the version I'd been testing with)

The procedure I've been using:

```
set v0.59.1 in the provider configuration
tfenv use 1.7.5
rm -rf .terraform* terraform.tfstate*
terraform init
terraform apply --auto-approve
terraform plan # expect no updates
set v0.62.0 in the provider configuration
terraform init --upgrade
terraform apply # expect state churn + error
tfenv use 1.9.0
terraform apply # expect no state churn, no error
```

I need to look into upstream terraform a bit. It might be worth trying things out with a newer version of terraform CLI.

**Comment by pyspiotr** [comment]
Hi Chris,
    It works now. Also with 0.64.0. Thank you for quick fix.
Cheers,
Piotr

**Comment by chrismarget-j** [comment]
Great!

Thank you for following up.
