### ISSUE TITLE
Generic systems - number of interfaces extension error

### ISSUE THREAD

**Issue by pyspiotr** [Juniper/terraform-provider-apstra#769]
Hello,
    I noticed an issue during port extension for the existing server connections. It can be done via GUI by adding new links to the leafs but once I try to do the same via terraform I got an error. Why terraform trys to delete generic system during port extension? 
"clear_cts_on_destroy" - looks like this does not change anything.

Regards,
Piotr
![Generic_system_port_extension_error](https://github.com/user-attachments/assets/d6731c89-48e4-498c-a145-b311fdf2bdf6)
![Generic_system_port_extension_1](https://github.com/user-attachments/assets/830398a7-1595-4eb8-acd3-9e31d09d488e)

**Comment by chrismarget-j** [comment]
Hi @pyspiotr,

Thank you for opening this issue.

### Part 1

> Why terraform trys to delete generic system during port extension?

Requiring a generic system to be replaced when links are changed is a compromise. There may be room for improvement here, but it's tricky.

Consider a scenario wherein the user modifies all links to connect to different switch ports or different switches. How should Terraform proceed?

If we begin delete the existing links, Apstra will destroy the generic system (orphan systems are not permitted), making it impossible to add the desired link.

If we begin by adding new links, we face a different problem which can be illustrated by the following pseudo-configuration:

```terraform
resource "apstra_datacenter_generic_system" "a" {
  name = "a"
  links = [
    {
      target_switch_id = "ssssssss"
      // target_switch_if_name = "xe-0/0/1" // this is the old configuration
      target_switch_if_name = "xe-0/0/2" // this is the new configuration
    }
  ]
}

resource "apstra_datacenter_generic_system" "b" {
  name = "b"
  links = [
    {
      target_switch_id = "ssssssss"
      // target_switch_if_name = "xe-0/0/2" // this is the old configuration
      target_switch_if_name = "xe-0/0/1" // this is the new configuration
    }
  ]
}
```

Here, we've edited the configuration to swap switch ports between two servers.

The "create new links first" strategy cannot work because we're at a deadlock: server A's new link cannot be created because the desired port is used by server B. Likewise, server "B"'s new link cannot be created because the desired port is used by server A.

There is definitely some nuanced wiggle-room here: Do we really need to destroy the server for *any* link change? Probably not. Merely adding a link doesn't cause these problems, and we can craft more intelligent rules. We're just not there yet.

### Part 2

> "clear_cts_on_destroy" - looks like this does not change anything.

We handle certain errors which block destruction of a generic system. This looks like one we haven't bumped into before (or maybe the error text has changed slightly). We'll need to explore further. This certainly looks like a bug.

What version of Apstra and Provider are you using?

**Comment by pyspiotr** [comment]
Hi Chris,
   Thank you for the explanation. We are using Apatra 4.2.1 and terraform
provider 0.64.0.
Regards,
Piotr

W dniu pt., 9.08.2024 o 17:33 chrismarget-j ***@***.***>
napisał(a):

**Comment by chrismarget-j** [comment]
Hi @pyspiotr,

Would you please share the before and after terraform configurations which led to this error?

Thanks!

**Comment by chrismarget-j** [comment]
Hi @pyspiotr,

I think this issue is resolved in v0.68.3. Would you please give it a try?

**Comment by pyspiotr** [comment]
Hi Chris,
  I have tried with version 0.68.3 and looks like link can be removed without issues but if I try to add it again after all I got attached error. When I re-run terraform apply it works.
![generic_systems_re-added_interfaces_error](https://github.com/user-attachments/assets/59c4d021-2500-4cdc-bcf3-584193c3a237)
![generic_systems_re-added_interfaces_second_apply](https://github.com/user-attachments/assets/69a96dce-95a0-4272-bd34-80849201d57e)

**Comment by chrismarget-j** [comment]
This conversation has moved to #802
