### ISSUE TITLE
Error: error creating new Link, if create link internal betwen external system

### ISSUE THREAD

**Issue by ihadi581** [Juniper/terraform-provider-apstra#789]
after create testing link p2p external system <> internal system, but error from transformation is not applicable.

╷
│ Error: error creating new Link
│ 
│   with apstra_freeform_link.blf1_vmxmpls,
│   on 0_provider.tf line 304, in resource "apstra_freeform_link" "blf1_vmxmpls":
│  304: resource "apstra_freeform_link" "blf1_vmxmpls" {
│ 
│ {"api_response":null,"config_blueprint_version":0,"errors":{"transformation_id":"Port transformation ID is not applicable for external system"},"error_code":422} - http response '' at
│ 'http://192.187.125.211:8443/api/blueprints/f1dd807a-9086-460a-b88a-16932aa6ced5/links?async=full&async=full'
╵

**Comment by chrismarget-j** [comment]
Hello @ihadi581, thank you for opening this issue.

It sounds like we should not mark `transformation_id` as a required attribute. I don't think we can validate whether or not the transform ID must be supplied. We'll need to note something like "required for internal systems" in the `MarkdownDescription`.

@bwJuniper would you please extend the tests so that this condition is created (and the tests fail), then get them passing again?

Seems like we may have the same problem with `interface_name` -- without a device profile, this field is meaningless for external systems, I think?

**Comment by bwJuniper** [comment]
I will get to work on this.

**Comment by bwJuniper** [comment]
We will need to make transformation_id a pointer as this can now be, and must be null for external systems(they do not have interfaces)
