### ISSUE TITLE
CT assignment: Not a valid application point

### ISSUE THREAD

**Issue by chrismarget-j** [Juniper/terraform-provider-apstra#802]
The following is from a comment on issue #769. Opening as a new issue because it seems unrelated to the underlying problem in #769:

I have tried with version 0.68.3 and looks like link can be removed without issues but if I try to add it again after all I got attached error. When I re-run terraform apply it works.
![generic_systems_re-added_interfaces_error](https://github.com/user-attachments/assets/59c4d021-2500-4cdc-bcf3-584193c3a237)
![generic_systems_re-added_interfaces_second_apply](https://github.com/user-attachments/assets/69a96dce-95a0-4272-bd34-80849201d57e)

_Originally posted by @pyspiotr in https://github.com/Juniper/terraform-provider-apstra/issues/769#issuecomment-2288296961_

**Comment by pyspiotr** [comment]
Hi Chris,
   Here are the steps:

1. Delete two links - output after apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place
  - destroy
 <= read (data resources)

Terraform will perform the following actions:

  # data.apstra_datacenter_interfaces_by_link_tag.DC1_AP_VNET_VDI_SERVER_GROUP_1 will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "apstra_datacenter_interfaces_by_link_tag" "DC1_AP_VNET_VDI_SERVER_GROUP_1" {
      + blueprint_id = "558b40a1-59ef-4a30-ad4e-9d6c054577ae"
      + graph_query  = (known after apply)
      + ids          = (known after apply)
      + tags         = [
          + "VNET_VDI_SERVER_GROUP_1",
        ]
    }

  # apstra_datacenter_connectivity_template_assignments.DC1_VNET_VDI_SERVER_GROUP_1 will be updated in-place
  ~ resource "apstra_datacenter_connectivity_template_assignments" "DC1_VNET_VDI_SERVER_GROUP_1" {
      ~ application_point_ids    = [
          - "jsSYU3UZmtR6HljdGnk",
        ] -> (known after apply)
      + ip_link_ids              = (known after apply)
        # (2 unchanged attributes hidden)
    }

  # apstra_datacenter_connectivity_template_assignments.DC1_VNET_VDI_SERVER_GROUP_1_NFS will be destroyed
  # (because apstra_datacenter_connectivity_template_assignments.DC1_VNET_VDI_SERVER_GROUP_1_NFS is not in configuration)
  - resource "apstra_datacenter_connectivity_template_assignments" "DC1_VNET_VDI_SERVER_GROUP_1_NFS" {
      - application_point_ids    = [
          - "cgMi-20rUylrfPt7yhg",
        ] -> null
      - blueprint_id             = "558b40a1-59ef-4a30-ad4e-9d6c054577ae" -> null
      - connectivity_template_id = "11949259-638e-11ef-81f0-617073747261" -> null
    }

  # apstra_datacenter_generic_system.DC1_LABS92135 will be updated in-place
  ~ resource "apstra_datacenter_generic_system" "DC1_LABS92135" {
        id                   = "EJubKRuzZmA48mvR-44"
      ~ links                = [
          - {
              - group_label                   = "LABS92135_bond1" -> null
              - lag_mode                      = "lacp_active" -> null
              - tags                          = [
                  - "10G",
                  - "SERVER",
                  - "VNET_VDI_SERVER_GROUP_1_NFS",
                ] -> null
              - target_switch_id              = "Zx82yoWoOYIeqXpQsaU" -> null
              - target_switch_if_name         = "xe-0/0/1" -> null
              - target_switch_if_transform_id = 2 -> null
            },
          - {
              - group_label                   = "LABS92135_bond1" -> null
              - lag_mode                      = "lacp_active" -> null
              - tags                          = [
                  - "10G",
                  - "SERVER",
                  - "VNET_VDI_SERVER_GROUP_1_NFS",
                ] -> null
              - target_switch_id              = "ypPvIFe-rU-GS5yRoRY" -> null
              - target_switch_if_name         = "xe-0/0/1" -> null
              - target_switch_if_transform_id = 2 -> null
            },
            # (2 unchanged elements hidden)
        ]
        name                 = "LABS92135"
        tags                 = [
            "SERVER",
        ]
        # (7 unchanged attributes hidden)
    }

Plan: 0 to add, 2 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

apstra_datacenter_connectivity_template_assignments.DC1_VNET_VDI_SERVER_GROUP_1_NFS: Destroying...
yeapstra_datacenter_connectivity_template_assignments.DC1_VNET_VDI_SERVER_GROUP_1_NFS: Destruction complete after 2s
apstra_datacenter_generic_system.DC1_LABS92135: Modifying... [id=EJubKRuzZmA48mvR-44]
apstra_datacenter_generic_system.DC1_LABS92135: Modifications complete after 1s [id=EJubKRuzZmA48mvR-44]
data.apstra_datacenter_interfaces_by_link_tag.DC1_AP_VNET_VDI_SERVER_GROUP_1: Reading...
data.apstra_datacenter_interfaces_by_link_tag.DC1_AP_VNET_VDI_SERVER_GROUP_1: Read complete after 0s

Apply complete! Resources: 0 added, 1 changed, 1 destroyed.

2. Re-added links and executed terraform apply


Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place
-/+ destroy and then create replacement
 <= read (data resources)

Terraform will perform the following actions:

  # data.apstra_datacenter_interfaces_by_link_tag.DC1_AP_VNET_VDI_SERVER_GROUP_1 will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "apstra_datacenter_interfaces_by_link_tag" "DC1_AP_VNET_VDI_SERVER_GROUP_1" {
      + blueprint_id = "558b40a1-59ef-4a30-ad4e-9d6c054577ae"
      + graph_query  = (known after apply)
      + ids          = (known after apply)
      + tags         = [
          + "VNET_VDI_SERVER_GROUP_1",
        ]
    }

  # data.apstra_datacenter_interfaces_by_link_tag.DC1_AP_VNET_VDI_SERVER_GROUP_1_NFS will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "apstra_datacenter_interfaces_by_link_tag" "DC1_AP_VNET_VDI_SERVER_GROUP_1_NFS" {
      + blueprint_id = "558b40a1-59ef-4a30-ad4e-9d6c054577ae"
      + graph_query  = (known after apply)
      + ids          = (known after apply)
      + tags         = [
          + "VNET_VDI_SERVER_GROUP_1_NFS",
        ]
    }

  # apstra_datacenter_connectivity_template_assignments.DC1_VNET_VDI_SERVER_GROUP_1 will be updated in-place
  ~ resource "apstra_datacenter_connectivity_template_assignments" "DC1_VNET_VDI_SERVER_GROUP_1" {
      ~ application_point_ids    = [
          - "jsSYU3UZmtR6HljdGnk",
        ] -> (known after apply)
      + ip_link_ids              = (known after apply)
        # (2 unchanged attributes hidden)
    }

  # apstra_datacenter_connectivity_template_assignments.DC1_VNET_VDI_SERVER_GROUP_1_NFS will be created
  + resource "apstra_datacenter_connectivity_template_assignments" "DC1_VNET_VDI_SERVER_GROUP_1_NFS" {
      + application_point_ids    = (known after apply)
      + blueprint_id             = "558b40a1-59ef-4a30-ad4e-9d6c054577ae"
      + connectivity_template_id = "11949259-638e-11ef-81f0-617073747261"
      + ip_link_ids              = (known after apply)
    }

  # apstra_datacenter_generic_system.DC1_LABS92135 must be replaced
-/+ resource "apstra_datacenter_generic_system" "DC1_LABS92135" {
      ~ id                   = "EJubKRuzZmA48mvR-44" -> (known after apply)
      ~ links                = [
          + { # forces replacement
              + group_label                   = "LABS92135_bond1"
              + lag_mode                      = "lacp_active"
              + tags                          = [
                  + "10G",
                  + "SERVER",
                  + "VNET_VDI_SERVER_GROUP_1_NFS",
                ]
              + target_switch_id              = "Zx82yoWoOYIeqXpQsaU"
              + target_switch_if_name         = "xe-0/0/1"
              + target_switch_if_transform_id = 2
            },
          + { # forces replacement
              + group_label                   = "LABS92135_bond1"
              + lag_mode                      = "lacp_active"
              + tags                          = [
                  + "10G",
                  + "SERVER",
                  + "VNET_VDI_SERVER_GROUP_1_NFS",
                ]
              + target_switch_id              = "ypPvIFe-rU-GS5yRoRY"
              + target_switch_if_name         = "xe-0/0/1"
              + target_switch_if_transform_id = 2
            },
            # (2 unchanged elements hidden)
        ]
        name                 = "LABS92135"
        tags                 = [
            "SERVER",
        ]
        # (7 unchanged attributes hidden)
    }

Plan: 2 to add, 1 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

apstra_datacenter_generic_system.DC1_LABS92135: Destroying... [id=EJubKRuzZmA48mvR-44]
apstra_datacenter_generic_system.DC1_LABS92135: Destruction complete after 4s
apstra_datacenter_generic_system.DC1_LABS92135: Creating...
apstra_datacenter_generic_system.DC1_LABS92135: Creation complete after 4s [id=shwSci-s3MrfVrt43_U]
data.apstra_datacenter_interfaces_by_link_tag.DC1_AP_VNET_VDI_SERVER_GROUP_1: Reading...
data.apstra_datacenter_interfaces_by_link_tag.DC1_AP_VNET_VDI_SERVER_GROUP_1_NFS: Reading...
data.apstra_datacenter_interfaces_by_link_tag.DC1_AP_VNET_VDI_SERVER_GROUP_1: Read complete after 0s
data.apstra_datacenter_interfaces_by_link_tag.DC1_AP_VNET_VDI_SERVER_GROUP_1_NFS: Read complete after 0s
apstra_datacenter_connectivity_template_assignments.DC1_VNET_VDI_SERVER_GROUP_1_NFS: Creating...
apstra_datacenter_connectivity_template_assignments.DC1_VNET_VDI_SERVER_GROUP_1: Modifying...
apstra_datacenter_connectivity_template_assignments.DC1_VNET_VDI_SERVER_GROUP_1_NFS: Creation complete after 1s
╷
│ Error: failed while assigning Connectivity Template "11948f39-638e-11ef-81f0-617073747261" to Application Points
│ 
│   with apstra_datacenter_connectivity_template_assignments.DC1_VNET_VDI_SERVER_GROUP_1,
│   on 03_ct_internal_generic_systems_assignment.tf line 6, in resource "apstra_datacenter_connectivity_template_assignments" "DC1_VNET_VDI_SERVER_GROUP_1":
│    6: resource "apstra_datacenter_connectivity_template_assignments" "DC1_VNET_VDI_SERVER_GROUP_1" {
│ 
│ {"api_response":null,"config_blueprint_version":0,"errors":{"application_points":{"1":{"policies":{"0":"Not a valid application point"}}}},"error_code":422} - http response '' at
│ 'http://apstra-lab/api/blueprints/558b40a1-59ef-4a30-ad4e-9d6c054577ae/obj-policy-batch-apply?async=full&async=full'
╵



3. Terraform Apply once agin - without any changes.

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # apstra_datacenter_connectivity_template_assignments.DC1_VNET_VDI_SERVER_GROUP_1 will be updated in-place
  ~ resource "apstra_datacenter_connectivity_template_assignments" "DC1_VNET_VDI_SERVER_GROUP_1" {
      ~ application_point_ids    = [
          + "FNP-dXYYCPyVXG9FVvY",
        ]
      + ip_link_ids              = (known after apply)
        # (2 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

apstra_datacenter_connectivity_template_assignments.DC1_VNET_VDI_SERVER_GROUP_1: Modifying...
apstra_datacenter_connectivity_template_assignments.DC1_VNET_VDI_SERVER_GROUP_1: Modifications complete after 1s

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

**Comment by chrismarget-j** [comment]
Hi @pyspiotr,

I can't reproduce these results without some example before/after configuration, but I think I might know what's going on here.

If you're deleting links from a generic system in the same project which discovers switch ports and then assigns CTs to those ports, then here's what might be happening:

1. planning phase plans deletion of server links
2. planning phase enumerates current switch ports
3. planning phase plans assignment of CTs to enumerated switch ports
4. apply phase deletes server links
5. apply phase cannot assign CT to switch ports which existed during `plan`, but were deleted in the previous step

There's not much we can do about this general category of problem from the provider side. The same thing would happen, for example, in AWS if you discovered (by data source) EC2 instances, planned EBS volume attachment for each, and also deleted an EC2 instance all in one shot: There would be an EBS volume attachment planned for an instance which is being terminated during that `apply`. It may or may not surface as an error depending on Terraform's execution order and timing.

One defense against this kind of problem is project structure. We have some users who do physical topology work (systems and links) in one project (separate terraform state file, etc...) and network services (VLANs, BGP sessions, etc...) in another project. Their CI system runs these projects independently, and in an order which ensures this problem never appears.

We're planning a provider update with a new feature which will help: It will make leaf/access switch port IDs (map of application point IDs keyed by `group_label`) an attribute of the `apstra_datacenter_generic_system` resource. This will eliminate the need for the data source which returns IDs that exist during `plan`, but which are eliminated during `apply`.

**Comment by chrismarget-j** [comment]
It occurs to me that you can validate the "link deleted before planned CT assignment completes" theory:

1. set up the required pre-conditions
2. run `terraform apply`, but do not yet type `yes` to approve the change
3. Optional - find link IDs in the graph explorer
  - Click on the "bug" icon in the "staging" tab
  - Enter `node(type='system', label='<server name from the web ui>')` in the query box
  - Hit `Execute`
  - Click on the `graph` tab
  - There should be only a single "dot" (graph node) on the screen. Grab it and move it into the corner of the screen.
  - Click `Show full blueprint`
  - Connected to the (now moved) system node/dot, you should find `interface` nodes. Connected to them are `link` nodes. Connected to the link nodes are other `interface` nodes.
  - So, `system` -> `interface` -> `link` <- `interface`
  - Note the IDs of the interface nodes at the other side of the link. These are the Application Points.
4. Type `yes` so that Terraform executes the changes.
5. Expect an error.
6. Hit `Refresh` in the Graph Explorer - have some application points vanished? been replaced?
7. Look in `Staging` -> `Tasks` for a failed (red) "Assign Connectivity Templates" task
8. Confirm that "Detailed Status" matches the error you got from terraform
9. Have a look at the "Request Data" : `data`->`application_points`->`id` - Does it reference an Application Point which disappeared from the graph?

**Comment by pyspiotr** [comment]
Hi Chris, 
    I followed your instruction and here are the results:
Until point 6 all is correct including application points been replaced.
Point 7. In Apstra all is good no errors nothing. I can see errors only on terraform side. 

Regards,
Piotr

**Comment by chrismarget-j** [comment]
Interesting. I'd have assumed we'd see a failed task in the log, but didn't actually confirm it. Some categories of failed API request don't get logged. I'm not sure about the rules here.

Did some of the application points disappear from the graph?

**Comment by chrismarget-j** [comment]
I've tested the situation (CT assignment API call referencing an application point which no longer exists) manually, and found the failed API call in the `tasks` screen.

Task list:
<img width="1093" alt="Screenshot 2024-08-26 at 10 07 23 AM" src="https://github.com/user-attachments/assets/d17bcf9e-7835-4d2d-b6c6-3f7a68179fe3">

Specific task detail page:
<img width="874" alt="Screenshot 2024-08-26 at 10 07 38 AM" src="https://github.com/user-attachments/assets/aab5ccfb-152e-434c-a6f7-39db1f3abf5c">

Detailed status containing the error we saw in terraform:
<img width="463" alt="Screenshot 2024-08-26 at 10 07 53 AM" src="https://github.com/user-attachments/assets/072d9a0d-c970-4c43-a635-34a3412da168">

I'm pretty confident that we understand what's happening, but I'm surprised you didn't see the failed task. Busy terraform pushed it to a subsequent page?

Javascript didn't refresh the list at the time you checked for it?

**Comment by pyspiotr** [comment]
Hi Chris, You are right. The error is there. Looks like I miss looked it as it was not visible in the main page. 
Regards, Piotr

**Comment by chrismarget-j** [comment]
Hi @pyspiotr,

Thank you for following up. Keep an eye out for the release which adds switch port IDs as attributes of the `apstra_datacenter_generic_system` resource.

It won't "fix" the problem you ran into here (really there's no fix for attempting to use an object while also deleting it), but the change will re-structure the workflow by eliminating the data lookup, making it much harder to wind up with this sort of problem.

I'm going to close this issue, but am happy to discuss your use case, challenges etc... You can always open another issue or ask your account team to set up a call.
