### ISSUE TITLE
Can not specify link speed when adding generic system

### ISSUE THREAD

**Issue by bauerclm** [Juniper/terraform-provider-apstra#952]
I am trying to add an external system to a rack with this code:

resource "apstra_datacenter_generic_system" "dci"{
 blueprint_id = apstra_datacenter_blueprint.datacenter.id
 hostname = "dci"
 name = "dci"
 external = true
 links = [
  {
  target_switch_id = local.rack1_leaf1.id
  target_switch_if_name = "et-0/0/52"
  target_switch_if_transform_id = 1
  }
 ]
}

the link is made but it creates a logical device for the external system that uses 40 gb speeds for the et interface but I want to make those links 100 gb. I don't see anywhere in the docs where I can specify the logical device of the external system or anywhere to specify the link speed.

**Comment by chrismarget-j** [comment]
Hi @bauerclm,

Thank you for opening this issue.

We don't require you to (allow you to? same difference, I guess) specify a logical device when creating a system within a blueprint because it has little to no effect on the outcome.

You'll note that the web UI, while it asks for a logical device, would produce the same result with "et-0/0/52" and transform # 1, regardless of what logical device you select. It will also allow you to make 100Gb/s connections to logical devices with only 40Gb/s interfaces.

If you look at a transaction sent by terraform (blueprint -> staged -> tasks -> task ID -> request data), you'll see that we send a [bogus logical device with a single 100Mb/s interface](https://github.com/Juniper/terraform-provider-apstra/blob/976bcb4a01f21dadaca0df330f12cb841e9149ee/apstra/blueprint/datacenter_generic_system.go#L171-L185) with every request, *every time, no matter what*.

Selecting the proper speed for each link really comes down to:
- the interface name
- the transform ID

Interface name obviously has implications where breakout is concerned (et-0/0/0 vs. et-0/0/0:0), but can also be relevant in some cases as a speed call-out. For example, Juniper MX304 2xLMIC16 MDP refers to the same physical interface as "ge", "xe" and "et" depending on the context.

If we ignore breakout scenarios, the selection usually comes down to the transform ID.

When you're not sure what name or transform to use (I never am), do a dry run in the web UI. You'll find that you're required to select/activate one of these colored buttons before the "Add Link" button becomes available. Making that selection is the web UI's way of specifying both of these fields.

<img width="875" alt="Screenshot 2024-10-31 at 9 30 25 PM" src="https://github.com/user-attachments/assets/9b5e07cf-c4ec-4083-b362-3dfa340ded28">
